import { escapeHtml } from "./format.js";

export function centralProductView(csrf: string, skills: boolean, clients: readonly { id: string; label: string }[]): string {
  const options = clients.map(client => '<option value="' + escapeHtml(client.id) + '" data-no-i18n>' + escapeHtml(client.label) + '</option>').join('');
  return '<section class="page-heading"><div><p class="eyebrow">YOUR AI WORKSPACE</p><h1>Services &amp; Skills</h1><p class="lede">Connect once. Choose what each AI client can use.</p></div><a class="button secondary" href="/admin/clients#add-client">Connect an AI client</a></section>'
    + '<div data-central-product data-csrf="' + escapeHtml(csrf) + '" data-skills="' + String(skills) + '">'
    + '<section class="central-start"><div><strong>1. Add capabilities</strong><p>Connect an MCP service or install a Skill.</p></div><div><strong>2. Review access</strong><p>Review tools and content before sharing.</p></div><div><strong>3. Use your AI client</strong><p>Choose capabilities and copy one connection URL.</p></div></section>'
    + '<p class="muted">Services and Skills work without a Runner. Add a Runner only for computer access.</p><p data-product-status role="status" aria-live="polite" data-no-i18n></p>'
    + '<nav class="central-tabs" aria-label="Capability library"><button type="button" class="button" data-central-tab="services" aria-pressed="true">MCP services</button>'
    + (skills ? '<button type="button" class="button secondary" data-central-tab="skills" aria-pressed="false">Skill library</button>' : '')
    + '<button type="button" class="button secondary" data-central-tab="access" aria-pressed="false">Client access</button><button type="button" class="button secondary" data-product-refresh>Refresh</button></nav>'
    + '<section data-central-panel="services"><div class="central-grid"><section class="panel"><h2>Connected services</h2><div data-service-list></div></section><section class="panel"><h2>Connect an MCP service</h2>' + '<p>Enter the service URL, choose how to sign in, and connect.</p><form data-service-create><label>MCP URL<input name="endpoint" type="url" required maxlength="2048" placeholder="https://mcp.example.com/mcp" autocomplete="url"></label><label>Authentication<select name="authentication"><option value="none">No authentication</option><option value="oauth">OAuth</option></select></label><label>Service name (optional)<input name="name" maxlength="64" placeholder="e.g. Team documentation"></label><p class="muted">OAuth opens the service sign-in page. Runmesh discovers its settings automatically.</p><button type="submit" class="button">Connect service</button></form><p class="muted">Review discovered tools before sharing them with any AI client.</p></section></div><section class="panel" data-service-review hidden></section></section>'
    + (skills ? '<section data-central-panel="skills" hidden><div class="central-grid"><section class="panel"><h2>Your Skills</h2><div data-skill-list></div></section><section class="panel"><h2>Install a Skill</h2><p>Select SKILL.md and its supporting text files, or select the whole Skill folder.</p><form data-skill-import><label>Skill files<input type="file" name="files" multiple></label><label>Skill folder<input type="file" name="folder" webkitdirectory multiple></label><p class="muted">The name and description are read from SKILL.md.</p><button class="button" type="submit">Install Skill</button></form><p class="muted">Installing a Skill saves its files. Scripts are never run during installation.</p></section></div><section class="panel" data-skill-review hidden></section></section>' : '')
    + '<section data-central-panel="access" hidden><section class="panel"><h2>Choose what your AI client can use</h2><p>Only reviewed capabilities appear here. Each client keeps its own permissions.</p><label>AI client<select data-client-select><option value="">Choose an AI client</option>' + options + '</select></label><div data-client-access></div><p><a href="/admin/clients#add-client">Create a new AI connection</a></p></section></section><noscript>Enable JavaScript to use the guided capability library.</noscript></div>';
}
