import { message } from "../i18n/messages.js";
import type { AdminData } from "./view-models.js";
import { arrayField, record, escapeHtml } from "./format.js";
import { runnerList, clientList, jobTable } from "./tables.js";
import { JOBS_EXPLANATION, jobSnapshotNote } from "./job-views.js";

export function overviewPage(data: AdminData, csrf: string): string {
  const online = data.runners.filter((runner) => runner.state === "online").length;
  const jobsAvailable = Array.isArray(data.snapshot.jobs) && Array.isArray(data.snapshot.runners);
  const activeJobs = arrayField(data.snapshot.runners).reduce<number>((total, value) => {
    const count = record(value)?.active_job_count;
    return total + (typeof count === "number" && Number.isSafeInteger(count) && count >= 0 ? count : 0);
  }, 0);
  return `<section class="page-heading"><div><p class="eyebrow">${message("text.control.plane.2", "en")}</p><h1>${message("nav.dashboard", "en")}</h1><p class="lede">${message("text.a.concise.view.of.connected.runtimes.clients.and.recent.work", "en")}</p></div><a class="button secondary" href="/admin">${message("action.refresh", "en")}</a></section><section class="metrics" aria-label="Summary"><div class="metric"><span class="metric-label">${message("text.active.mcp.clients", "en")}</span><strong class="metric-value">${data.clients.filter((client) => client.revoked_at_ms === null).length}</strong><span class="metric-meta">${data.clients.length} configured</span></div><div class="metric"><span class="metric-label">${message("text.online.total.runners", "en")}</span><strong class="metric-value">${online} / ${data.runners.length}</strong><span class="metric-meta"><span class="status-dot ${online > 0 ? "online" : "offline"}"></span> ${online} connected</span></div><div class="metric"><span class="metric-label">${message("text.active.shell.jobs", "en")}</span><strong class="metric-value">${jobsAvailable ? activeJobs : "—"}</strong><span class="metric-meta">${message("text.last.recorded.status", "en")}</span></div><div class="metric"><span class="metric-label">${message("text.recent.jobs", "en")}</span><strong class="metric-value">${jobsAvailable ? data.jobs.length : "—"}</strong><span class="metric-meta">${message("text.recorded", "en")}</span></div></section><div class="grid-two"><section class="panel"><div class="section-title"><h2>${message("text.recent.runners", "en")}</h2><a href="/admin/runners">${message("text.view.all", "en")}</a></div>${runnerList(data.runners.slice(0, 5))}</section><section class="panel"><div class="section-title"><h2>${message("text.recent.mcp.clients", "en")}</h2><a href="/admin/clients">${message("text.view.all", "en")}</a></div>${clientList(data.clients.slice(0, 5))}</section></div><section class="panel"><div class="section-title"><h2>${message("text.recent.jobs", "en")}</h2><a href="/admin/runners">${message("text.runner.activity", "en")}</a></div><p class="muted">${JOBS_EXPLANATION}</p>${jobSnapshotNote()}${jobsAvailable ? jobTable(data.jobs.slice(0, 10)) : data.notices.some((n) => n.title === 'Job snapshot unavailable') ? '<p class="empty">Job metadata is temporarily unavailable.</p>' : '<p class="muted">Jobs not loaded. Select a Runner and click Load / Refresh.</p>'}</section><form class="hidden" method="post" action="/admin/logout"><input type="hidden" name="csrf_token" value="${escapeHtml(csrf)}"></form>`;
}

export function settingsPage(csrf: string): string { return `<section class="page-heading"><div><p class="eyebrow">${message("text.workspace.administration", "en")}</p><h1>${message("nav.settings", "en")}</h1><p class="lede">${message("text.keep.operator.notes.here.credentials.and.secrets.are.never.displayed", "en")}</p></div></section><div class="grid-two"><section class="panel"><div class="section-title"><h2>${message("text.change.password", "en")}</h2></div><form method="post" action="/admin/password" class="stack settings-form"><input type="hidden" name="csrf_token" value="${escapeHtml(csrf)}"><label>${message("text.current.password", "en")}<input type="password" name="current_password" required autocomplete="current-password"></label><label>${message("text.new.password", "en")}<input type="password" name="password" minlength="12" required autocomplete="new-password"></label><label>${message("text.confirm.new.password", "en")}<input type="password" name="confirm_password" minlength="12" required autocomplete="new-password"></label><button class="button">${message("text.change.password", "en")}</button></form></section><section class="panel danger-panel"><div class="section-title"><h2 class="danger-title">${message("text.operator.notes", "en")}</h2></div><p class="muted settings-note">${message("text.deployment.notes.belong.in.your.deployment.system.this.dashboard.intentionally.stores.no.n", "en")}</p><div class="logout-box"><form method="post" action="/admin/logout" class="stack"><input type="hidden" name="csrf_token" value="${escapeHtml(csrf)}"><button class="button secondary">${message("text.log.out", "en")}</button></form></div></section></div>`; }
