import { message } from "../i18n/messages.js";
import type { AdminData } from "./view-models.js";
import { arrayField, record, escapeHtml } from "./format.js";
import { runnerList, clientList, clientCredentialBadge, jobTable } from "./tables.js";
import { JOBS_EXPLANATION, jobSnapshotNote } from "./job-views.js";

export function productOverviewPage(data: AdminData): string {
  const connections = data.clients.slice(0, 5).map(client => '<li><a class="card-row" href="/admin/clients/' + encodeURIComponent(client.client_id) + '"><div class="card-row-main"><span class="strong" data-no-i18n>' + escapeHtml(client.label) + '</span><span class="card-row-sub">' + clientCredentialBadge(client.revoked_at_ms !== null) + '</span></div><span class="row-arrow">→</span></a></li>').join('');
  return '<section class="page-heading"><div><p class="eyebrow">YOUR AI WORKSPACE</p><h1>Make your AI client more useful</h1><p class="lede">Start with shared services and Skills. Computer access is optional.</p></div><a class="button" href="/admin/clients#add-client">Connect an AI client</a></section>'
    + '<div class="central-grid"><section class="panel"><h2>1. Add capabilities</h2><p>Connect an MCP service or import a Skill.</p><p>Review tools and content before sharing.</p><a class="button" href="/admin/central">Explore services and Skills</a></section>'
    + '<section class="panel"><h2>2. Connect your AI client</h2><p>Create a connection for each AI client to use your shared capabilities.</p><a class="button secondary" href="/admin/clients">Manage AI connections</a></section></div>'
    + '<section class="panel"><div class="section-title"><h2>Your AI connections</h2><div class="actions"><a href="/admin/clients">View all</a><a class="button secondary" href="/admin">Refresh</a></div></div>' + (connections ? '<ul class="item-list">' + connections + '</ul>' : '<p class="empty">No AI connections yet. Create one to start using your capabilities.</p>') + '</section>'
    + '<details class="panel"><summary>Optional computer access</summary><p>Add a Runner when your AI client needs to work with files or run commands on your computer.</p><div class="actions"><a class="button secondary" href="/admin/runners">Manage computers and activity</a><a class="button secondary" href="/admin?history=1">View computer activity</a></div>' + (data.runners.length ? runnerList(data.runners.slice(0, 5)) : '') + '</details>';
}

export function overviewPage(data: AdminData, csrf: string): string {
  const online = data.runners.filter((runner) => runner.state === "online").length;
  const jobsAvailable = Array.isArray(data.snapshot.jobs) && Array.isArray(data.snapshot.runners);
  const activeJobs = arrayField(data.snapshot.runners).reduce<number>((total, value) => {
    const count = record(value)?.active_job_count;
    return total + (typeof count === "number" && Number.isSafeInteger(count) && count >= 0 ? count : 0);
  }, 0);
  return `<section class="page-heading"><div><p class="eyebrow">${message("text.control.plane.2", "en")}</p><h1>${message("nav.dashboard", "en")}</h1><p class="lede">${message("text.a.concise.view.of.connected.runtimes.clients.and.recent.work", "en")}</p></div><a class="button secondary" href="/admin">${message("action.refresh", "en")}</a></section><section class="metrics" aria-label="Summary"><div class="metric"><span class="metric-label">${message("text.active.mcp.clients", "en")}</span><strong class="metric-value">${data.clients.filter((client) => client.revoked_at_ms === null).length}</strong><span class="metric-meta">${data.clients.length} configured</span></div><div class="metric"><span class="metric-label">${message("text.online.total.runners", "en")}</span><strong class="metric-value">${online} / ${data.runners.length}</strong><span class="metric-meta"><span class="status-dot ${online > 0 ? "online" : "offline"}"></span> ${online} connected</span></div><div class="metric"><span class="metric-label">${message("text.active.shell.jobs", "en")}</span><strong class="metric-value">${jobsAvailable ? activeJobs : "—"}</strong><span class="metric-meta">${message("text.last.recorded.status", "en")}</span></div><div class="metric"><span class="metric-label">${message("text.recent.jobs", "en")}</span><strong class="metric-value">${jobsAvailable ? data.jobs.length : "—"}</strong><span class="metric-meta">${message("text.recorded", "en")}</span></div></section><div class="grid-two"><section class="panel"><div class="section-title"><h2>${message("text.recent.runners", "en")}</h2><a href="/admin/runners">${message("text.view.all", "en")}</a></div>${runnerList(data.runners.slice(0, 5))}</section><section class="panel"><div class="section-title"><h2>${message("text.recent.mcp.clients", "en")}</h2><a href="/admin/clients">${message("text.view.all", "en")}</a></div>${clientList(data.clients.slice(0, 5))}</section></div><section class="panel"><div class="section-title"><h2>${message("text.recent.jobs", "en")}</h2><a href="/admin/runners">${message("text.runner.activity", "en")}</a></div><p class="muted">${JOBS_EXPLANATION}</p>${jobSnapshotNote()}${jobsAvailable ? jobTable(data.jobs.slice(0, 10)) : data.notices.some((n) => n.title === 'Job snapshot unavailable') ? '<p class="empty">Job metadata is temporarily unavailable.</p>' : '<p class="muted">Jobs not loaded. Select a Runner and click Load / Refresh.</p>'}</section><form class="hidden" method="post" action="/admin/logout"><input type="hidden" name="csrf_token" value="${escapeHtml(csrf)}"></form>`;
}

export function settingsPage(csrf: string): string { return `<section class="page-heading"><div><p class="eyebrow">${message("text.workspace.administration", "en")}</p><h1>${message("nav.settings", "en")}</h1><p class="lede">${message("text.keep.operator.notes.here.credentials.and.secrets.are.never.displayed", "en")}</p></div></section><div class="grid-two"><section class="panel"><div class="section-title"><h2>${message("text.change.password", "en")}</h2></div><form method="post" action="/admin/password" class="stack settings-form"><input type="hidden" name="csrf_token" value="${escapeHtml(csrf)}"><label>${message("text.current.password", "en")}<input type="password" name="current_password" required autocomplete="current-password"></label><label>${message("text.new.password", "en")}<input type="password" name="password" minlength="12" required autocomplete="new-password"></label><label>${message("text.confirm.new.password", "en")}<input type="password" name="confirm_password" minlength="12" required autocomplete="new-password"></label><button class="button">${message("text.change.password", "en")}</button></form></section><section class="panel danger-panel"><div class="section-title"><h2 class="danger-title">${message("text.operator.notes", "en")}</h2></div><p class="muted settings-note">${message("text.deployment.notes.belong.in.your.deployment.system.this.dashboard.intentionally.stores.no.n", "en")}</p><div class="logout-box"><form method="post" action="/admin/logout" class="stack"><input type="hidden" name="csrf_token" value="${escapeHtml(csrf)}"><button class="button secondary">${message("text.log.out", "en")}</button></form></div></section></div>`; }
