
  (function(){
function applyLocale(locale){document.documentElement.lang=locale;document.querySelectorAll('[data-lang-toggle]').forEach(function(link){link.setAttribute('aria-current',link.getAttribute('data-lang-toggle')===locale?'true':'false')})}
function requestedLocale(){return document.documentElement.lang==='zh-CN'?'zh-CN':'en'}
function rememberLocale(locale){document.cookie='runmesh_lang='+locale+'; Max-Age=31536000; Path=/; SameSite=Lax'}
 document.querySelectorAll('[data-lang-toggle]').forEach(function(link){link.addEventListener('click',function(event){var locale=link.getAttribute('data-lang-toggle')||'en';rememberLocale(locale);var url=new URL(location.href);url.searchParams.set('lang',locale);event.preventDefault();location.href=url.toString()})});
var locale=requestedLocale();if(new URLSearchParams(location.search).has('lang'))rememberLocale(locale);applyLocale(locale);
function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text);var area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy')}catch(_){}area.remove();return Promise.resolve()}
function copyValue(button){var panel=button.hasAttribute('data-copy-source')&&button.closest('[role=tabpanel]');if(panel){var code=panel.querySelector('pre code');return code?(code.textContent||''):''}var value=button.getAttribute('data-copy');return value===null?'':value}
document.querySelectorAll('[data-copy],[data-copy-source]').forEach(function(button){button.addEventListener('click',function(){var result=copyText(copyValue(button));var mark=function(){button.textContent=document.documentElement.lang==='zh-CN'?'已复制':'Copied';button.classList.add('copied')};if(result&&typeof result.then==='function')result.then(mark,function(){});else mark()})});
function stabilizeTabPanels(){document.querySelectorAll('.enrollment-command-panels').forEach(function(container){var panels=Array.prototype.slice.call(container.querySelectorAll('[data-panel]'));if(!panels.length)return;var max=0;panels.forEach(function(panel){var wasHidden=panel.hidden;panel.hidden=false;max=Math.max(max,panel.offsetHeight);panel.hidden=wasHidden});if(max>0)panels.forEach(function(panel){panel.style.minHeight=max+'px'})})}
document.querySelectorAll('[data-tab]').forEach(function(tab){tab.addEventListener('click',function(){var target=tab.getAttribute('data-tab');var top=tab.getBoundingClientRect().top;document.querySelectorAll('[data-tab]').forEach(function(item){item.setAttribute('aria-selected',String(item===tab));item.tabIndex=item===tab?0:-1});document.querySelectorAll('[data-panel]').forEach(function(panel){panel.hidden=panel.getAttribute('data-panel')!==target});var delta=tab.getBoundingClientRect().top-top;if(delta)window.scrollBy(0,delta)});tab.addEventListener('keydown',function(event){if(event.key==='ArrowLeft'||event.key==='ArrowRight'){var tabs=Array.prototype.slice.call(document.querySelectorAll('[data-tab]'));var next=tabs[(tabs.indexOf(tab)+(event.key==='ArrowRight'?1:tabs.length-1))%tabs.length];next.focus();next.click()}})});stabilizeTabPanels();window.addEventListener('resize',function(){stabilizeTabPanels()});
document.querySelectorAll('.pwd-toggle-btn').forEach(function(btn){btn.addEventListener('click',function(){var wrap=btn.closest('.password-input-wrap');if(!wrap)return;var input=wrap.querySelector('input');if(!input)return;var isPwd=input.type==='password';input.type=isPwd?'text':'password';var isZh=document.documentElement.lang==='zh-CN';var buttonLabel=isPwd?(isZh?'隐藏密码':'Hide password'):(isZh?'显示密码':'Show password');btn.setAttribute('aria-label',buttonLabel);btn.setAttribute('title',buttonLabel);btn.innerHTML=isPwd?'<svg class="eye-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>':'<svg class="eye-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>'})});
 document.querySelectorAll('form.login-form').forEach(function(form){form.addEventListener('submit',function(){var btn=form.querySelector('.login-submit-btn');if(!btn||btn.disabled)return;var isZh=document.documentElement.lang==='zh-CN';var isSetup=form.getAttribute('action')==='/setup';var loadingText=isSetup?(isZh?'正在初始化...':'Initializing...'):(isZh?'正在登录...':'Signing in...');var origWidth=btn.offsetWidth;btn.style.width=origWidth>0?(origWidth+'px'):'100%';btn.disabled=true;btn.textContent=loadingText;try{form.submit()}catch(e){}})});
function syncExecutionMode(form){var selected=form.querySelector('input[name="execution_mode"]:checked');if(!selected)selected=form.querySelector('select[name="execution_mode"]');var privileged=!!selected&&selected.value==='privileged_host';var confirmation=form.querySelector('[data-privileged-confirmation]');var warning=form.querySelector('.privileged-host-warning');var modeFieldset=form.querySelector('[data-execution-mode-form]');var reuse=!!modeFieldset&&modeFieldset.getAttribute('data-reuse-privileged-confirmation')==='true';if(confirmation)confirmation.required=privileged&&!reuse;if(warning)warning.hidden=!privileged||reuse}
 document.querySelectorAll('form').forEach(function(form){var controls=form.querySelectorAll('input[name="execution_mode"],select[name="execution_mode"]');if(!controls.length)return;controls.forEach(function(input){input.addEventListener('change',function(){syncExecutionMode(form)})});syncExecutionMode(form)});
// Keep the application chrome mounted while admin pages stream into cached workspace containers.
function updateActiveNavigation(path){var normalized=path.replace(/\/$/,'')||'/admin';document.querySelectorAll('.control-nav a').forEach(function(link){var href=link.getAttribute('href')||'';var active=href==='/admin'?normalized==='/admin':normalized===href||normalized.indexOf(href+'/')===0;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current')})}
function pageKey(url){return url.pathname+(url.search||'')}
function pageRoot(node){return node&&node.classList&&node.classList.contains('shell')?node:(node&&node.closest&&node.closest('.shell'))||node}
function pageContainer(root,key){var container=document.createElement('div');container.className='admin-page-container';container.setAttribute('data-page-container','');container.setAttribute('data-page-key',key);container.setAttribute('aria-hidden','true');container.appendChild(root);return container}
function ensurePageViewport(){var viewport=document.querySelector('[data-admin-viewport]');var active=document.querySelector('#main-content');if(!active)return viewport;var root=pageRoot(active);if(!root)return viewport;if(!viewport){viewport=document.createElement('div');viewport.className='admin-viewport';viewport.setAttribute('data-admin-viewport','');root.parentNode.insertBefore(viewport,root);var initial=pageContainer(root,pageKey(new URL(location.href)));initial.setAttribute('data-page-title',document.title||'');initial.classList.add('is-active');initial.setAttribute('aria-hidden','false');viewport.appendChild(initial)}else if(!root.closest('[data-page-container]')){var initial=pageContainer(root,pageKey(new URL(location.href)));initial.setAttribute('data-page-title',document.title||'');initial.classList.add('is-active');initial.setAttribute('aria-hidden','false');viewport.appendChild(initial)}return viewport}
function setActivePage(container,focus){var viewport=ensurePageViewport();if(!viewport||!container)return;var containers=Array.prototype.slice.call(viewport.querySelectorAll('[data-page-container]'));var previous=viewport.querySelector('[data-page-container].is-active');containers.forEach(function(item){var active=item===container;var wasPrevious=item===previous&&item!==container;item.classList.toggle('is-active',active);if(wasPrevious){item.classList.remove('is-leaving')}else if(active)item.classList.remove('is-leaving');else item.classList.remove('is-leaving');item.setAttribute('aria-hidden',active?'false':'true');item.inert=!active;var main=item.id==='main-content'?item:item.querySelector('#main-content');if(active){if(!main)main=item.tagName==='MAIN'?item:item.querySelector('main');if(main)main.id='main-content'}else if(main)main.removeAttribute('id')});viewport.style.minHeight=Math.max.apply(Math,[0].concat(containers.map(function(item){return item.offsetHeight||0})))+'px';if(focus){var main=container.id==='main-content'?container:container.querySelector('#main-content')||container.querySelector('main');if(main&&typeof main.focus==='function')main.focus({preventScroll:true})}}
function bindDynamicContent(root){
  if(!root)return;
  root.querySelectorAll('[data-copy],[data-copy-source]').forEach(function(button){if(button.__runmeshBound)return;button.__runmeshBound=true;button.addEventListener('click',function(){var result=copyText(copyValue(button));var mark=function(){button.textContent=document.documentElement.lang==='zh-CN'?'已复制':'Copied';button.classList.add('copied')};if(result&&typeof result.then==='function')result.then(mark,function(){});else mark()})});
  root.querySelectorAll('[data-tab]').forEach(function(tab){if(tab.__runmeshBound)return;tab.__runmeshBound=true;tab.addEventListener('click',function(){var target=tab.getAttribute('data-tab');var top=tab.getBoundingClientRect().top;root.querySelectorAll('[data-tab]').forEach(function(item){item.setAttribute('aria-selected',String(item===tab));item.tabIndex=item===tab?0:-1});root.querySelectorAll('[data-panel]').forEach(function(panel){panel.hidden=panel.getAttribute('data-panel')!==target});var delta=tab.getBoundingClientRect().top-top;if(delta)window.scrollBy(0,delta)});tab.addEventListener('keydown',function(event){if(event.key==='ArrowLeft'||event.key==='ArrowRight'){var tabs=Array.prototype.slice.call(root.querySelectorAll('[data-tab]'));var next=tabs[(tabs.indexOf(tab)+(event.key==='ArrowRight'?1:tabs.length-1))%tabs.length];next.focus();next.click()}})});
  root.querySelectorAll('.pwd-toggle-btn').forEach(function(btn){if(btn.__runmeshBound)return;btn.__runmeshBound=true;btn.addEventListener('click',function(){var wrap=btn.closest('.password-input-wrap');if(!wrap)return;var input=wrap.querySelector('input');if(!input)return;var isPwd=input.type==='password';input.type=isPwd?'text':'password';var label=isPwd?(document.documentElement.lang==='zh-CN'?'隐藏密码':'Hide password'):(document.documentElement.lang==='zh-CN'?'显示密码':'Show password');btn.setAttribute('aria-label',label);btn.setAttribute('title',label)})});
  root.querySelectorAll('form').forEach(function(form){var controls=form.querySelectorAll('input[name="execution_mode"],select[name="execution_mode"]');if(!controls.length)return;controls.forEach(function(input){if(input.__runmeshBound)return;input.__runmeshBound=true;input.addEventListener('change',function(){syncExecutionMode(form)})});syncExecutionMode(form)});
  bindFeatureAlert(root);
  stabilizeTabPanels();
}
function setupDynamicNavigation(){document.querySelectorAll('a[href^="/admin"]').forEach(function(link){if(link.__runmeshNavBound)return;link.__runmeshNavBound=true;link.addEventListener('click',function(event){if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||link.hasAttribute('download')||link.target==='_blank')return;var target=new URL(link.href,location.href);if(target.origin!==location.origin)return;if(target.pathname===location.pathname&&target.search===location.search&&target.hash)return;event.preventDefault();loadAdminPage(target,pageKey(target)!==pageKey(new URL(location.href)))})})}
function mountAdminPage(nextRoot,title,key,viewport,shouldPush,url){
  nextRoot.removeAttribute('id');var container=pageContainer(nextRoot,key);container.setAttribute('data-page-title',title||'');
  viewport=ensurePageViewport();viewport.appendChild(container);document.title=title||document.title;
  bindDynamicContent(container);bindFeatureAlert(container);setupDynamicNavigation();
  if(shouldPush)history.pushState({runmeshAdmin:true},'',url.pathname+url.search+url.hash);
  setActivePage(container,true);updateActiveNavigation(url.pathname);applyLocale(requestedLocale());
  // Retain only the newly rendered page, not stale forms or sensitive job logs.
  Array.prototype.slice.call(viewport.querySelectorAll('[data-page-container]')).forEach(function(item){if(item!==container)item.remove()});
  viewport.style.minHeight=(container.offsetHeight||0)+'px';
}
function loadAdminPage(url,shouldPush){
  if(window.__runmeshLoading){window.__runmeshQueuedUrl=url;window.__runmeshQueuedPush=shouldPush;return}
  window.__runmeshLoading=true;var key=pageKey(url),viewport=ensurePageViewport(),current=document.querySelector('#main-content');
  if(current)current.setAttribute('aria-busy','true');
  return fetch(url.href,{credentials:'same-origin',cache:'no-store'}).then(function(response){
    if(!response.ok)throw new Error('HTTP '+response.status);return response.text();
  }).then(function(markup){
    var parsed=new DOMParser().parseFromString(markup,'text/html'),next=parsed.querySelector('#main-content');
    if(parsed.documentElement&&parsed.documentElement.lang&&parsed.documentElement.lang!==document.documentElement.lang){location.href=url.href;return;}
    if(!next)throw new Error('main content missing');var nextRoot=pageRoot(next);if(!nextRoot)throw new Error('page root missing');
    mountAdminPage(nextRoot,parsed.title||'',key,viewport,shouldPush,url);
  }).catch(function(error){
    console.error('Runmesh navigation failed',error);location.href=url.href;
  }).finally(function(){
    window.__runmeshLoading=false;var active=document.querySelector('#main-content');if(active)active.removeAttribute('aria-busy');
    if(window.__runmeshQueuedUrl){var queued=window.__runmeshQueuedUrl,queuedPush=window.__runmeshQueuedPush;window.__runmeshQueuedUrl=null;loadAdminPage(queued,queuedPush)}
  });
}
function bindFeatureAlert(root){var dialog=root.querySelector('.feature-alert-dialog');if(!dialog||dialog.__runmeshBound)return;dialog.__runmeshBound=true;dialog.addEventListener('click',function(event){if(event.target===dialog)dialog.close()})}
 ensurePageViewport();var initialContainer=document.querySelector('[data-page-container].is-active');if(initialContainer){stabilizeTabPanels();setActivePage(initialContainer,false)}
 window.addEventListener('popstate',function(){loadAdminPage(new URL(location.href),false)});setupDynamicNavigation();window.__runmeshDynamicNavigation=true;bindFeatureAlert(document);
  })();
